# Generated by Django 5.2.17 on 2026-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_redepermitida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ADMIN_EMPRESA', 'Admin da Empresa'), ('DIRETOR', 'Diretor'), ('ESPECIAL', 'Usuário Especial'), ('NORMAL', 'Usuário Normal')], default='NORMAL', max_length=20),
        ),
    ]
